export {default as banner} from './Banner.svg'
export {default as logo} from './Logo.png'
// export {default as banner} from './Banner.svg'
// export {default as banner} from './Banner.svg'
// export {default as banner} from './Banner.svg'
// export {default as banner} from './Banner.svg'
// export {default as banner} from './Banner.svg'
// export {default as banner} from './Banner.svg'
// export {default as banner} from './Banner.svg'
// export {default as banner} from './Banner.svg'